### ISSUE TITLE
[New]: 2024，使用房车这一年

### ISSUE THREAD

**Issue by ops-coffee** [saveweb/review-2024#8]
### 文章链接

https://blog.ops-coffee.cn/r/2024-rv-travel-camping-and-vanlife

**Comment by taranakineko** [comment]
已经在先前的 https://github.com/saveweb/review-2024/commit/53aef2583f6824a8ab9e8341ed558b5f0710b077 中人工收录

总之感谢您的支持，祝新的一年快乐~
